"""
Simple Airfoil Generation Example

This script demonstrates the most basic usage of DeepFoil:
generating airfoils with specific thickness and camber.

Run from the DEEPFOIL_DISTRIBUTION directory:
    python examples/simple_generation.py
"""

import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from latent_interpreter import LatentInterpreter
import numpy as np


def main():
    print("=" * 80)
    print("SIMPLE AIRFOIL GENERATION EXAMPLE")
    print("=" * 80)

    # Initialize the interpreter
    print("\n1. Loading model and dataset...")
    interpreter = LatentInterpreter()
    print(f"   Model loaded! Latent dimension: {interpreter.latent_dim}")
    print(f"   Training data: {len(interpreter.dataset)} airfoils")

    # Define target specifications
    target_thickness = 0.12  # 12% thickness
    target_camber = 0.03     # 3% camber
    num_samples = 5          # Generate 5 airfoils

    print(f"\n2. Generating airfoils with:")
    print(f"   Target thickness: {target_thickness:.1%}")
    print(f"   Target camber: {target_camber:.1%}")
    print(f"   Number of samples: {num_samples}")

    # Generate
    airfoils, latent_codes = interpreter.generate_with_target_features(
        target_thickness=target_thickness,
        target_camber=target_camber,
        num_samples=num_samples
    )

    if airfoils is None:
        print("\n   ERROR: No matching airfoils found!")
        print("   Try adjusting your target specifications.")
        return

    print(f"\n   Success! Generated {len(airfoils)} airfoils.")

    # Create output directory
    output_dir = Path("examples_output/simple_generation")
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n3. Saving airfoils to: {output_dir}/")

    # Save each airfoil
    for i, airfoil in enumerate(airfoils):
        # Reshape to (200, 2) coordinates
        coords = airfoil.numpy().reshape(200, 2)

        # Save as .dat file (XFOIL format)
        dat_file = output_dir / f"airfoil_{i+1:03d}.dat"
        with open(dat_file, 'w') as f:
            f.write(f"Generated by DeepFoil - Simple Example\n")
            f.write(f"Target: thickness={target_thickness:.1%}, camber={target_camber:.1%}\n")
            for x, y in coords:
                f.write(f"{x:.6f}  {y:.6f}\n")

        # Save as .npy file (NumPy format)
        npy_file = output_dir / f"airfoil_{i+1:03d}.npy"
        np.save(npy_file, coords)

        # Calculate actual thickness and camber
        upper = coords[:100]
        lower = coords[100:]
        actual_thickness = np.max(upper[:, 1] - lower[:, 1])
        camber_line = (upper[:, 1] + lower[:, 1]) / 2
        actual_camber = np.max(np.abs(camber_line))

        print(f"   Airfoil {i+1}: thickness={actual_thickness:.2%}, camber={actual_camber:.2%}")

    # Save latent codes for reproducibility
    latent_file = output_dir / "latent_codes.npy"
    np.save(latent_file, latent_codes.numpy())
    print(f"\n4. Saved latent codes to: {latent_file}")

    print("\n" + "=" * 80)
    print("EXAMPLE COMPLETE!")
    print("=" * 80)
    print("\nYou can now:")
    print("  1. Open the .dat files in XFOIL for aerodynamic analysis")
    print("  2. Load the .npy files in Python for further processing")
    print("  3. Use the latent codes to reproduce these exact airfoils")
    print("\nNext steps:")
    print("  - Try different thickness and camber values")
    print("  - Increase num_samples to get more options")
    print("  - Run other examples: batch_processing.py, custom_workflow.py")
    print()


if __name__ == "__main__":
    main()
